# Generated by Django 6.0.1 on 2026-01-27 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this backup target (e.g., 'nyxmon')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of what this backup covers",
                    ),
                ),
                (
                    "fastdeploy_service",
                    models.CharField(
                        help_text="Name of the FastDeploy service to use for backups",
                        max_length=100,
                    ),
                ),
                (
                    "db_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to SQLite database to back up",
                        max_length=500,
                    ),
                ),
                (
                    "backup_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional files/directories to include in backup",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Cron schedule expression (e.g., '0 2 * * *' for 2am daily)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days to retain backups"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=600,
                        help_text="Maximum time to wait for backup to complete",
                    ),
                ),
                (
                    "storage_bucket",
                    models.CharField(
                        default="backups",
                        help_text="MinIO bucket for storing backups",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "backup_target",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("api", "API"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        help_text="User or system that triggered this backup",
                        max_length=100,
                    ),
                ),
                (
                    "fastdeploy_deployment_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FastDeploy deployment ID for this backup",
                        null=True,
                    ),
                ),
                ("storage_bucket", models.CharField(blank=True, max_length=100)),
                (
                    "storage_key",
                    models.CharField(
                        blank=True,
                        help_text="Object key in MinIO (e.g., 'nyxmon/2024-01-15T02-00-00.tar.gz')",
                        max_length=500,
                    ),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                (
                    "logs",
                    models.TextField(
                        blank=True, help_text="Captured output from the backup process"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="backups.backuptarget",
                    ),
                ),
            ],
            options={
                "db_table": "backup_run",
                "ordering": ["-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "running"])),
                        fields=("target",),
                        name="unique_active_backup_per_target",
                    )
                ],
            },
        ),
    ]
