# Generated by Django 6.0.1 on 2026-01-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprun",
            name="file_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of files included in the backup",
                null=True,
            ),
        ),
    ]
