# Generated by Django 6.0.1 on 2026-01-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_add_file_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuptarget",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Emoji or icon identifier for this target (e.g., '🏠' or '📊')",
                max_length=50,
            ),
        ),
    ]
