# Generated by Django 6.0.1 on 2026-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0005_add_endpoint_key_and_restore_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuptarget",
            name="service_token",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JWT token for FastDeploy service. If set, overrides token from FASTDEPLOY_ENDPOINTS. Leave blank to use endpoint/default token.",
            ),
        ),
    ]
