# Generated by Django 6.0.1 on 2026-03-02

from django.db import migrations, models
from django.db.models import Q


GENERIC_PATHS_MODE = "generic_paths"
SERVICE_OWNED_MODE = "service_owned"


def backfill_target_modes_and_service_metadata(apps, schema_editor):
    BackupTarget = apps.get_model("backups", "BackupTarget")

    service_owned_targets = [
        "fastdeploy",
        "marina-staging",
        "python-podcast-staging",
        "homepage-staging",
        "homeassistant",
        "homepage-production-db",
        "python-podcast-production-db",
        "homepage-media",
        "python-podcast-media",
        "paperless",
    ]
    generic_targets = [
        "nyxmon",
        "homelab",
        "echoport",
        "openclaw",
    ]

    # Mode mapping for all known targets (unknown rows remain default generic_paths).
    BackupTarget.objects.filter(name__in=service_owned_targets).update(target_mode=SERVICE_OWNED_MODE)
    BackupTarget.objects.filter(name__in=generic_targets).update(target_mode=GENERIC_PATHS_MODE)

    # Backfill restore-critical metadata for generic targets when missing.
    service_name_map = {
        "nyxmon": "nyxmon.service",
        "homelab": "homelab.service",
        "echoport": "echoport.service",
        "openclaw": "openclaw.service",
    }
    restore_owner_map = {
        "nyxmon": "nyxmon:nyxmon",
        "homelab": "homelab:homelab",
        "echoport": "echoport:echoport",
        "openclaw": "1000:1000",
    }

    for target_name, service_name in service_name_map.items():
        BackupTarget.objects.filter(name=target_name).filter(
            Q(service_name__isnull=True) | Q(service_name="")
        ).update(service_name=service_name)

    for target_name, restore_owner in restore_owner_map.items():
        BackupTarget.objects.filter(name=target_name).filter(
            Q(restore_owner__isnull=True) | Q(restore_owner="")
        ).update(restore_owner=restore_owner)

    # Cleanup known placeholder db_path values on service-owned media targets.
    BackupTarget.objects.filter(
        name__in=["homepage-media", "python-podcast-media"],
        target_mode=SERVICE_OWNED_MODE,
    ).update(db_path="")


def reverse_target_mode_backfill(apps, schema_editor):
    BackupTarget = apps.get_model("backups", "BackupTarget")
    # Schema-safe reverse: restore pre-migration mode behavior.
    # Intentionally does not revert data cleanup/backfills from forward migration
    # (e.g., media placeholder db_path values and restored service metadata).
    # If full historical metadata is needed, perform manual repair.
    BackupTarget.objects.all().update(target_mode=GENERIC_PATHS_MODE)


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0006_add_service_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuptarget",
            name="target_mode",
            field=models.CharField(
                choices=[("generic_paths", "Generic paths"), ("service_owned", "Service-owned")],
                default="generic_paths",
                help_text="Target contract mode. 'Generic paths' requires service_name and at least one of db_path/backup_files. 'Service-owned' allows empty source fields.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_target_modes_and_service_metadata,
            reverse_target_mode_backfill,
        ),
    ]
