# Generated by Django 6.0.1 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0007_add_target_mode_and_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuptarget",
            name="schedule_required",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Require this active target to have a schedule. Missing schedules "
                    "are rejected on save and reported as unhealthy if configuration "
                    "drift bypasses validation."
                ),
            ),
        ),
    ]
