# Generated by Django 6.0.1 on 2026-10-06

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


class CaseInsensitiveNameCollisionError(RuntimeError):
    """Existing backup targets differ only by case; the constraint cannot be added."""


def check_name_collisions(apps, schema_editor):
    """
    Refuse to add the case-insensitive constraint while collisions exist.

    Uses the database's own LOWER() so the check matches exactly what the
    unique index will enforce. Nothing is renamed or deleted automatically:
    which target is canonical is an operator decision.
    """
    BackupTarget = apps.get_model("backups", "BackupTarget")
    db_alias = schema_editor.connection.alias
    targets = BackupTarget.objects.using(db_alias)
    colliding = (
        targets.annotate(name_ci=Lower("name"))
        .values("name_ci")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("name_ci", flat=True)
    )
    groups = []
    for name_ci in colliding:
        rows = (
            targets.annotate(name_ci=Lower("name"))
            .filter(name_ci=name_ci)
            .order_by("id")
            .values_list("id", "name")
        )
        groups.append(", ".join(f"'{name}' (id {pk})" for pk, name in rows))
    if groups:
        raise CaseInsensitiveNameCollisionError(
            "Cannot make backup target names case-insensitively unique: "
            "these targets differ only by case: "
            + "; ".join(sorted(groups))
            + ". Rename or delete the duplicates (Django admin or shell), "
            "then run migrate again. No data was changed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0008_backuptarget_schedule_required"),
    ]

    operations = [
        migrations.RunPython(check_name_collisions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="backuptarget",
            name="name",
            field=models.CharField(
                help_text=(
                    "Unique identifier for this backup target (e.g., 'nyxmon'). "
                    "Names are unique regardless of case."
                ),
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="backuptarget",
            constraint=models.UniqueConstraint(
                Lower("name"),
                name="unique_backup_target_name_ci",
                violation_error_message=(
                    "A backup target with this name already exists "
                    "(names are compared case-insensitively)."
                ),
            ),
        ),
    ]
