# Generated by Django 6.0.1 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backups", "0009_backuptarget_name_case_insensitive_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuptarget",
            name="schedule",
            field=models.CharField(
                blank=True,
                help_text="Cron expression in UTC (e.g. '0 2 * * *' = 02:00 UTC daily)",
                max_length=100,
            ),
        ),
    ]
